docker_apt_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common

docker_repository: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
docker_gpg_key: "https://download.docker.com/linux/ubuntu/gpg"
docker_package_name: "docker-ce"
docker_user: "{{ ansible_user }}"
