---
roles:
  - name: deusops-role
    src: git+https://gitlab.com/ansible-deusops-roles/deusops-role.git
    scm: git
    version: main

  - name: nginx-role
    src: git+https://gitlab.com/ansible-deusops-roles/nginx-role.git
    scm: git
    version: main